// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw5XRUsWolAKMvJ0YPBgcYrLBWlNcTZ4Y',
    appId: '1:411859961693:web:63796b90b00c46cbd08ab4',
    messagingSenderId: '411859961693',
    projectId: 'buzztalk-31b21',
    authDomain: 'buzztalk-31b21.firebaseapp.com',
    storageBucket: 'buzztalk-31b21.appspot.com',
    measurementId: 'G-3X5CX85ZPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa3XY4B0QEGxjVXIvPQqOrMJgnX7ZuVIc',
    appId: '1:411859961693:android:02a5c70efa30f501d08ab4',
    messagingSenderId: '411859961693',
    projectId: 'buzztalk-31b21',
    storageBucket: 'buzztalk-31b21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAgqNpUR0dDZrlg8Zdg2DhpUcnP7dQhF4',
    appId: '1:411859961693:ios:a9dfcc1c3fe08a54d08ab4',
    messagingSenderId: '411859961693',
    projectId: 'buzztalk-31b21',
    storageBucket: 'buzztalk-31b21.appspot.com',
    iosBundleId: 'com.example.buzztalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAgqNpUR0dDZrlg8Zdg2DhpUcnP7dQhF4',
    appId: '1:411859961693:ios:a9dfcc1c3fe08a54d08ab4',
    messagingSenderId: '411859961693',
    projectId: 'buzztalk-31b21',
    storageBucket: 'buzztalk-31b21.appspot.com',
    iosBundleId: 'com.example.buzztalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw5XRUsWolAKMvJ0YPBgcYrLBWlNcTZ4Y',
    appId: '1:411859961693:web:59d04b45abebb5fbd08ab4',
    messagingSenderId: '411859961693',
    projectId: 'buzztalk-31b21',
    authDomain: 'buzztalk-31b21.firebaseapp.com',
    storageBucket: 'buzztalk-31b21.appspot.com',
    measurementId: 'G-8KMWNJJNYP',
  );
}
